### PR TITLE
Tests refactoring

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Here are the changes made:

1. The Speco test has been divided into three separate tests:
1.1. `AllTransformationStepsTest`
1.2. `SpecoEoTest`
1.3. `SpecoXmirTest`
2. Some minor fixes have been applied, such as renaming variables and restricting the visibility of certain methods.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@advasileva Could you have a look, please?

**Comment by advasileva** [comment]
@volodya-lombrozo LGTM! Thanks a lot for refactoring, the decomposition by classes is really better than it was before

**Comment by volodya-lombrozo** [comment]
@yegor256 Could I ask you to merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
