### PR TITLE
test: unit xmir test for extension transformation

### LINKED ISSUE #51: 1-3-extension.xsl:29-31: add unit-test for...
The puzzle `47-276d8114` from #47 has to be resolved: 

https://github.com/objectionary/speco/blob/d3260f62cc2875b79dd473bcebce0213fa4d63cc/src/main/resources/org/eolang/speco/1-3-extension.xsl#L29-L31

The puzzle was created by @rultor on 15-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by advasileva**
Add unit test for `1-3-extension.xsl` transformation. Closes #51

### CODE REVIEW

**Comment by advasileva** [comment]
@yegor256 I rewrote this test to `xax`, PR is ready for review

**Comment by yegor256** [comment]
@volodya-lombrozo pls help us review this one

**Review by volodya-lombrozo — COMMENTED** [review]
@advasileva I'm not sure if we have to show `<aoi/>` section in tests. Please correct me, if I'm wrong.

Everything else looks good to me. Thanks!

**Comment by volodya-lombrozo** [comment]
@yegor256 Looks good to me, can you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by advasileva** [comment]
@yegor256 @volodya-lombrozo Thanks!

**Pull request merged**
