### PR TITLE
refactor: transformations for rules 1-2

### PR DESCRIPTION
**Pull request by advasileva**
In accordance to #46 

The purpose of this PR was to refactor the existing `xsl`-transformations so that it would be more convenient to write the rest (now only 2 rules out of 7 are written, I don't want to produce dozens of files, so I try to reduce their number).

At the same time, I fixed a bug in the transformation, so now the `convertsFromEo` integration tests pass (there was a separate @todo for this, but pdd did not create an issue).

The format of the `<speco/>` section has also changed a bit (remove unused attribute), so I changed the tests for `xmir`.

Obviously, we need separate tests for each transformation, but I suppose it's better to add them in a separate PR)

### CODE REVIEW

**Comment by advasileva** [comment]
@yegor256 this PR is ready for review

**Comment by yegor256** [comment]
@volodya-lombrozo please, take a look

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@advasileva Please, add puzzles for **each** transformation - to add tests.

**Comment by advasileva** [comment]
> @advasileva Please, add puzzles for **each** transformation - to add tests.

@volodya-lombrozo done

**Review by volodya-lombrozo — APPROVED** [review]
@advasileva Thanks. Looks good to me.
@yegor256 Could you merge that changes, please?

**Comment by advasileva** [comment]
@volodya-lombrozo thanks. Should I add tests for created puzzles in single PR or divide it into 4 PRs?

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo thanks. Should I add tests for created puzzles in single PR or divide it into 4 PRs?

@advasileva Divide

**Comment by advasileva** [comment]
@yegor256 this PR can be merged, at the same time we can check the work of pdd

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0pdd** [comment]
@advasileva 4 puzzles [#50](https://github.com/objectionary/speco/issues/50), [#51](https://github.com/objectionary/speco/issues/51), [#52](https://github.com/objectionary/speco/issues/52), [#53](https://github.com/objectionary/speco/issues/53) are still not solved.

**Comment by advasileva** [comment]
@yegor256 cool, thanks!

**Comment by 0pdd** [comment]
@advasileva 3 puzzles [#50](https://github.com/objectionary/speco/issues/50), [#51](https://github.com/objectionary/speco/issues/51), [#53](https://github.com/objectionary/speco/issues/53) are still not solved; solved: [#52](https://github.com/objectionary/speco/issues/52).

**Comment by 0pdd** [comment]
@advasileva 2 puzzles [#50](https://github.com/objectionary/speco/issues/50), [#53](https://github.com/objectionary/speco/issues/53) are still not solved; solved: [#51](https://github.com/objectionary/speco/issues/51), [#52](https://github.com/objectionary/speco/issues/52).

**Comment by 0pdd** [comment]
@advasileva the puzzle [#50](https://github.com/objectionary/speco/issues/50) is still not solved; solved: [#51](https://github.com/objectionary/speco/issues/51), [#52](https://github.com/objectionary/speco/issues/52), [#53](https://github.com/objectionary/speco/issues/53).

**Comment by 0pdd** [comment]
@advasileva all 4 puzzles are solved here: [#50](https://github.com/objectionary/speco/issues/50), [#51](https://github.com/objectionary/speco/issues/51), [#52](https://github.com/objectionary/speco/issues/52), [#53](https://github.com/objectionary/speco/issues/53).

**Pull request merged**
