### PR TITLE
tests for rule 4

### LINKED ISSUE #80: 4-1-fence-tuples.xsl:28-31: add unit-test for...
The puzzle `68-f9ee8553` from #68 has to be resolved: 

https://github.com/objectionary/speco/blob/166a4bc858dd9c77c78ac2b1054129056b63e73a/src/main/resources/org/eolang/speco/4-1-fence-tuples.xsl#L28-L31

The puzzle was created by @rultor on 28-Feb-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by advasileva**
Add `xmir` unit test for `4-1-fence-tuples.xsl` transformation and `eo` unit and compilation test with `counter`. Closes #80. 

23 tests passes now.

### CODE REVIEW

**Comment by advasileva** [comment]
@yegor256 This PR is ready for review

**Comment by yegor256** [comment]
@rultor merge

**Comment by advasileva** [comment]
@yegor256 I renamed `array` to `tuple`, the tests should stop failing. Retry merge, please.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
