### PR TITLE
clear xax

### LINKED ISSUE #86: clear `xax` tests
I think it will be nicer if we remove unnecessary objects (e.g. printers) and attributes (e.g. `line` and `pos`) in `xax` tests.

### PR DESCRIPTION
**Pull request by advasileva**
Remove unnecessary objects and attributes from `xax` tests. Closes #86

### CODE REVIEW

**Comment by advasileva** [comment]
@yegor256 This PR is ready for review

**Comment by yegor256** [comment]
@rultor merge

**Comment by advasileva** [comment]
@yegor256 Please, try to merge this PR, it is simpler than the one that failed today, and does not change stuck test

**Comment by yegor256** [comment]
@rultor merge

**Comment by advasileva** [comment]
@yegor256 try merge pls

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
